feat: integrate api to homepage
speedclimbing/website pull request #15
Opened 2023-01-11 19:35 UTC by lamorak13

Integration of the crawer api to the homepage. 
Used for:
- world records
- all time world rankings
- recent events

Also made SwitchButton more universally usable and implemented needed types

2023-01-11 19:44 UTC, lamorak13 commented
![grafik](https://user-images.githubusercontent.com/69404447/211902284-768714a1-9c01-458f-90c4-61bd49b2f2a2.png)

Upon fetching, all dates get converted into JS Date Objects
The question is, whether the same should be done with names, i.e. capitalizing them (this is currently done as needed) and if we should create global format filters to apply to dates (to avoid code duplication)

2023-01-16 13:47 UTC, dorianim requested changes

2023-01-16 13:47 UTC, dorianim commented on src/compnonents/home/RankingsTable.svelte
> +			{#each worldRankingsMale as ranking, index (index)}
```suggestion
			{#each (male ? worldRankingsMale:woldRankingsFemale) as ranking, index (index)}
```

Please do this like this (or similar) to avoid the code duplication.

2023-01-17 14:22 UTC, lamorak13 commented on src/compnonents/home/RankingsTable.svelte
> +			{#each worldRankingsMale as ranking, index (index)}
Oh yes I really like this solution! This makes it way cleaner

2023-01-18 12:23 UTC, dorianim approved these changes

2023-01-18 12:24 UTC, dorianim approved these changes

2023-01-18 12:25 UTC, dorianim approved these changes

2023-01-18 12:26 UTC, merged