Feat: competititon overview page
speedclimbing/website pull request #20
Opened 2023-01-19 15:01 UTC by lamorak13

2023-03-24 19:50 UTC, dorianim requested changes
Looks great overall, just some minor comments :)

2023-03-24 19:50 UTC, dorianim commented on src/compnonents/shared/PrimaryButton.svelte
> +		goto(link);
I think, the generic Primary button should not include a goto option. Maybe, we could create a LinkButton which does this instead?

2023-03-24 19:50 UTC, dorianim commented on src/routes/competition/+page.svelte
> +		handleSearch(year, name, nation, leagueId);
Please add some kind of busy indication here by using a promise and an await block. Similar as in the athlete search here:
https://github.com/speedclimbing/website/blob/2534de190acab415af4414f40d6f573e7501898d/src/routes/athlete/%2Bpage.svelte#L23

2023-03-24 19:50 UTC, dorianim commented on src/routes/competition/+page.svelte
> +	const debounce = (newValue: string) => {
Please use `utils/debounce` like in the athlete search here:
https://github.com/speedclimbing/website/blob/2534de190acab415af4414f40d6f573e7501898d/src/routes/athlete/%2Bpage.ts#L23

2023-03-24 19:50 UTC, dorianim commented on src/routes/competition/+page.svelte
> +			{#each [...Array(10).keys()] as number}
Not so sure about this one. I think, it would be better to use the seasons from the database.

2023-03-24 20:20 UTC, lamorak13 commented on src/routes/competition/+page.svelte
> +	const debounce = (newValue: string) => {
Yes, I wanted to do this. How can I get the changes from main into my branch?

2023-03-24 20:21 UTC, lamorak13 commented on src/routes/competition/+page.svelte
> +		handleSearch(year, name, nation, leagueId);
Sure, right now the load times are not slow enough to need it but I guess it makes sense in the long run. I'll probably just use the pattern that you used :)

2023-03-24 20:24 UTC, lamorak13 commented on src/compnonents/shared/PrimaryButton.svelte
> +		goto(link);
Sure, no problem. The goto option is just the default. you can pass any function to the component if you want to implement a different behaviour. 
What would you suggest as default function instead?

2023-03-24 20:32 UTC, dorianim commented on src/compnonents/shared/PrimaryButton.svelte
> +		goto(link);
I'd suggest using a void function `() => {}`

2023-03-24 20:35 UTC, dorianim commented on src/routes/competition/+page.svelte
> +	const debounce = (newValue: string) => {
You'll have to resolve the conflicts in the header and primarybutton components.
You can merge locally using `git fetch origin dev` and after that `git merge origin/dev`.

2023-03-24 20:36 UTC, dorianim commented on src/routes/competition/+page.svelte
> +			{#each [...Array(10).keys()] as number}
I think, that would be a good thing! Currently, it would not be possible to see that event at all.

2023-03-30 15:59 UTC, dorianim requested changes
Looks very good overall! Just some suggestions.

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +<script lang="ts">
Please rename to CompetitionCalendar

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +		let calendarEl: HTMLElement = document.getElementById('calendar')!;
Please use a bind:this instead of document.getElementById (see https://svelte.dev/tutorial/bind-this )

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +						if (calendar.getDate().getFullYear() != year) {
Please change to return early style to avoid indentation
`if (calendar.getDate().getFullYear() === year) return;`

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +						if (calendar.getDate().getFullYear() != year) {
same as above, return early instead of indented block

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +						navigator.clipboard.writeText('http://ics.speedclimbing.org/');
Some suggestions here:
- use https
- add the current search query
- show a little popup explaining what the link is and what to do with it
- rephrase text on button to be clearer to people who don't know what an ics calendar is

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/shared/SwitchButton.svelte
> +			on:click={() => handleClickLeft()}
```suggestion
			on:click={handleClickLeft}
```

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/shared/SwitchButton.svelte
> +			on:click={(e) => handleClickRight()}
```suggestion
			on:click={handleClickRight}
```

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.svelte
> +	<div class="flex gap-[10px] mt-10">
Please make this responsive:
![image](https://user-images.githubusercontent.com/30153207/228893008-d72393a3-ec03-4d11-ab6c-e30a8cb47059.png)

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.svelte
> +				if (target instanceof HTMLInputElement) {
please return early

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.svelte
> +
Please handle the promise here and only pass a `Competition[]` to the components.

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.svelte
> +	<EventCalendar {competitions} {viewCalendar} bind:year />
Please remove the viewCalendar prop and use an if to render one or the other

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.svelte
> +					await debounce();
Is this required? debounce is already called in _loadCompetitions

2023-03-30 15:59 UTC, dorianim commented on src/routes/competition/+page.ts
> +			new URLSearchParams({
This could be broken out into a function (_paramsToUrlSearchParams or similar)

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/CompetitionGrid.svelte
> +	export let competitions: Competition[] | Promise<Competition[]>;
Please change type to `Competition[]`. Handling the promise should be done in `+page.ts`

2023-03-30 15:59 UTC, dorianim commented on src/compnonents/competitions/CompetitionGrid.svelte
> +	export let viewCalendar: boolean;
Please remove. This should be done in `+page.ts`

2023-03-30 16:07 UTC, lamorak13 commented on src/compnonents/competitions/CompetitionGrid.svelte
> +	export let competitions: Competition[] | Promise<Competition[]>;
I used the same pattern as the athlete page. Initially, I had the type as only Competition[], but then it is not possible to work with the {#await} block, since there is no promise to await. Thats why I changed it to accept both types. 
Alternatively we could also introduce a new state called loading, which is set to true, whenever data is loaded and which then shows the busy indication.

2023-03-30 17:20 UTC, dorianim commented on src/compnonents/competitions/CompetitionGrid.svelte
> +	export let competitions: Competition[] | Promise<Competition[]>;
The pattern is ok, but I think, the await should be in `+page.ts`. See [here](https://github.com/speedclimbing/website/pull/20#discussion_r1153469270).

2023-03-30 17:32 UTC, dorianim commented on src/routes/competition/+page.svelte
> +					await debounce();
Ahh, I see. The problem is that you are always loading the leagues and the _loadLeagues function has no debounce. It might be best to just load the leagues when the year changes.

2023-03-30 18:08 UTC, lamorak13 commented on src/compnonents/competitions/EventCalendar.svelte
> +		let calendarEl: HTMLElement = document.getElementById('calendar')!;
Works very well. This really saves a lot of code and logic, but know the performance is not as good, since the component has to be mounted and unmounted every time viewCalendar set.

2023-03-30 18:26 UTC, lamorak13 commented on src/compnonents/competitions/CompetitionGrid.svelte
> +	export let competitions: Competition[] | Promise<Competition[]>;
Sure, makes sense. But if I factor out the await block in the +page, then the CompetitionGrid has nearly no content in it. Might need to delete the component.

2023-03-30 19:38 UTC, dorianim commented on src/compnonents/competitions/EventCalendar.svelte
> +		let calendarEl: HTMLElement = document.getElementById('calendar')!;
How bad is it? Is it noticable? In that case we should use getElementById

2023-03-30 19:41 UTC, dorianim commented on src/routes/competition/+page.svelte
> +					await debounce();
Hmm, ok. But in that case, I'd prefer to have the `await debounce()` in the line before you call the load function and not in the component. I think, usinf bind for the value is much cleaner.

2023-04-05 10:05 UTC, dorianim requested changes
Looks great! Just a few minor things, mostly about the new modal.

2023-04-05 10:05 UTC, dorianim commented on src/routes/competition/+page.ts
> +	await debounce();
```suggestion
```
This should not be required because it is already done in the filter bar.

2023-04-05 10:05 UTC, dorianim commented on src/routes/competition/FilterBar.svelte
> +		await debounce();
```suggestion
		if(!await debounce()) return;
```
This will have to be changed to accommodate for the changes in #28

2023-04-05 16:16 UTC, lamorak13 commented on src/routes/competition/+page.ts
> +	await debounce();
no, this is the debounce for the leadCompetition function which is needed for the busy indication when loading new comps. The other debounce in the filter is for the name input. There was no way to factor this out to +page.svelte without creating more problems than needed

2023-04-05 16:22 UTC, lamorak13 commented on src/routes/competition/FilterBar.svelte
> +		await debounce();
Yes, we can merge the debounce PR and then pull the changes in here

2023-04-05 16:38 UTC, dorianim commented on src/routes/competition/+page.ts
> +	await debounce();
I don't understand that. For me, it works perfectly fine without this line.
Only the year picker acts a little strange, but that shouldn't be hard to fix.

2023-04-05 20:27 UTC, lamorak13 commented on src/compnonents/competitions/CalendarSubscriptionModal.svelte
> +<script lang="ts">
The modal in the preview seems to have different classes applied to it than the modal on my local pc even though I didnt add them. For exampl the backdrop of the modal has position flex instead of fixed and has overflow hidden on it. 

I checked and there were some updates to flowbite svelte today and yesterday. Can you check on your pc if it is responsive?

2023-04-05 21:54 UTC, dorianim approved these changes
Finally :)

2023-04-05 22:00 UTC, merged