Feat: about-us page
speedclimbing/website pull request #37
Opened 2023-04-29 00:45 UTC by dorianim

This adds a new page ate `/about-us` with some information about the team.

- [ ] some information about team members
- [ ] contributors
- [ ] contact form
- [ ] imprint
- [ ] privacy policy

2023-05-01 08:11 UTC, lamorak13 requested changes

2023-05-01 08:11 UTC, lamorak13 commented on src/compnonents/shared/AnchorPoint.svelte
> +<a class="none anchor" {id} href="/">#</a>
remove none class

2023-05-01 08:11 UTC, lamorak13 commented on src/compnonents/shared/AnchorPoint.svelte
> +	a.anchor {
Use tailwind classes for better consistency

2023-05-01 08:13 UTC, lamorak13 commented
I really like the design and the idea to also display contributors. The only thing I would consider in terms of design is to make alignment consistent in the "who we are section".

2023-05-01 08:46 UTC, dorianim commented on src/compnonents/shared/AnchorPoint.svelte
> +	a.anchor {
You are completely right!

2023-05-03 10:05 UTC, lamorak13 approved these changes
Like it!

2023-05-03 10:09 UTC, merged