Feat: new images
speedclimbing/website pull request #38
Opened 2023-05-03 10:17 UTC by dorianim

- Feat: load image from s3 bucket
- Feat: first draft of carousel
- Feat: add second hero image

2023-05-06 20:03 UTC, lamorak13 requested changes

2023-05-06 20:03 UTC, lamorak13 commented on src/compnonents/home/CarouselComponent.svelte
> +		background-image: linear-gradient(0deg, rgba(17, 24, 39, 0.6), rgba(17, 24, 39, 0.6));
since the background no longer includes an image, it would be better to just use a bg-... class for the backround overlay. I would also make it a bit darker, since some of the images are quite bright.

2023-05-06 20:30 UTC, dorianim commented on src/routes/+page.server.ts
> +	const [data, heroImages] = await Promise.all([dataPromise, heroImagesPromise]);
I did this to make the two promises run in parallel, see: https://stackoverflow.com/questions/35612428/call-async-await-functions-in-parallel

That makes it faster, because most of the time of fetch is spent waiting for data from the server and not actual cpu work.

2023-05-06 20:32 UTC, dorianim commented on src/compnonents/home/CarouselComponent.svelte
> +		| {
Prettier adds that automatically, so I'd just leave it there. Does not seem to have any effect.

2023-05-14 08:40 UTC, lamorak13 commented on src/routes/+page.server.ts
> +	const [data, heroImages] = await Promise.all([dataPromise, heroImagesPromise]);
Ah ok got it

2023-05-14 09:21 UTC, lamorak13 approved these changes
Seems good now :)

2023-05-14 09:25 UTC, merged