Feat: global stats page all time
speedclimbing/website pull request #39
Opened 2023-05-06 22:06 UTC by lamorak13

2023-05-13 17:43 UTC, lamorak13 commented
I now also refactored all tables into one Table component. Did the same for the container divs in the stats page, the line charts and some other recurring elements. Also structured the shared components into subfolders for easier access.

2023-05-14 13:41 UTC, dorianim requested changes
We need to discuss the handling of table data.
Otherwise, it looks very good! :+1:

2023-05-14 13:41 UTC, dorianim commented on src/app.postcss
> +.custom-tooltip {
Please refactor this to use tailwind classes, where possible.

2023-05-14 13:41 UTC, dorianim commented on src/compnonents/shared/Table.svelte
> +	export let tableHeadings: string[] = [];
Please rename this to `columnNames`

2023-05-14 13:41 UTC, dorianim commented on src/compnonents/shared/Table.svelte
> +	export let tableObjects: object[];
I think, it would be cleaner to directly pass `string[] | number[] | TableCellComponent[]`.

2023-05-14 13:41 UTC, dorianim commented on src/compnonents/shared/Table.svelte
> +						{#if value instanceof Object}
```suggestion
						{#if value instanceof TableCellComponent}
```

2023-05-14 13:41 UTC, dorianim commented on src/compnonents/stats/LineChart.svelte
> +	export let data: any[];
Please use a more specific type, eg.
```suggestion
	export let data: { [key: string]: string | number | null }[];
```

2023-05-14 13:41 UTC, dorianim commented on src/routes/stats/+page.svelte
> +	let showSeasonStats: boolean = true;
Maybe, we should use a season variable instead, which receives a year. Like that, we could add a dropdown to select the season to show

2023-05-14 13:41 UTC, dorianim commented on src/utils/chartConfig.ts
> +	if (!tooltipEl) {
Please change this to return early

2023-05-16 21:06 UTC, dorianim commented on src/compnonents/home/RankingsTable.svelte
> +		r.competition_date.toLocaleDateString('de-DE', {
This will be handled in a new issue

2023-05-16 22:47 UTC, lamorak13 commented on src/routes/stats/+page.svelte
> +	let showSeasonStats: boolean = true;
I left this one and added a new variable, since undefined | number cannot be used as value variable for our selects

2023-05-17 04:25 UTC, dorianim approved these changes

2023-05-17 15:03 UTC, merged