Fix: some competition calendar things
speedclimbing/website pull request #40
Opened 2023-05-09 16:07 UTC by dorianim

- [ ] use league_group for calendar (needs https://github.com/speedclimbing/microservices/pull/35)
- [ ] fix calendar behaviour

2023-05-14 13:40 UTC, lamorak13 requested changes
Looks very good so far

2023-05-14 13:40 UTC, lamorak13 commented on src/routes/competition/+page.svelte
> +		disabled={viewCalendar}
I wouldnt disable the year select if the calendar is active. If the other selects are active this one should be as well

2023-05-14 13:40 UTC, lamorak13 commented on src/routes/competition/+page.svelte
> +			year = calendarDate.getFullYear();
Maybe there is some way to refactor this so that it is easier to understand what happens

2023-05-14 18:21 UTC, dorianim commented on src/routes/competition/+page.svelte
> +			year = calendarDate.getFullYear();
I rewrote this part, hope it is better to  understand now :)

2023-05-16 20:20 UTC, lamorak13 approved these changes

2023-05-16 20:23 UTC, merged