Feat: first draft of stats detail page
speedclimbing/website pull request #59
Opened 2023-05-22 09:32 UTC by dorianim

2023-07-03 17:49 UTC, lamorak13 requested changes
I just checked everything you did .... really impressive. I could follow most of the changes but maybe it would be good to get together one time so that you can update me on what changed. 

Also love the way you handled the stats details page from a UX perspective! :)

2023-07-05 07:55 UTC, dorianim commented on src/components/shared/buttons/AlternativeButton.svelte
> +{#if onClick}
Sometimes, we need a button, when we want to execute JavaScript after a click, and sometimes, we need an `a` when we want to navigate.
But you are right, it's not spotless at the moment. Maybe we should use two visually different components for those two use cases?

2023-07-05 07:58 UTC, dorianim commented on src/components/stats/SmartTable.svelte
> +<script lang="ts">
Yes, exactly. The name might be a bit confusing, if you have a better idea, I'm happy to change it :)

2023-07-14 12:09 UTC, lamorak13 approved these changes
LGTM!

2023-07-14 12:09 UTC, merged