Chore/improve seo
speedclimbing/website pull request #61
Opened 2023-07-14 14:01 UTC by allesklardy

- Added title and meta descriptions tags to all pages. 
- Added sitemap.xml to web root #55 
- Updated Images to .webp. Reduced Home Page load by 2MB

2023-07-14 14:02 UTC, allesklardy commented
Sorry for the conflicts :))

2023-07-17 10:12 UTC, dorianim requested changes
Thanks! Looks great overall, but I's like to rephrase some of the descriptions :)

Also, I think, we should generate the sitemap dynamically instead of having a static xml file. This has the benefit, that we can generate entries for all athletes/competitions once we have pages for them.

2023-07-17 10:12 UTC, dorianim commented on src/app.html
> +		<meta name="keywords" content="Speedclimbing Statistics, Worldranking, IFSC" />
Shouldn't keywords be page-specific as well?

2023-07-17 10:12 UTC, dorianim commented on src/routes/+page.svelte
> +		content="Your Page for the current and past statistics about Speedclimbing.
```suggestion
		content="speedclimbing.org - the platform to get information about speedclimbing for everyone - from newbies to professionals. 
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/+page.svelte
> +		See everything about the current world records, the latest tournaments and the performance of the athlets."
```suggestion
		Get to know everything about the current world records, latest competitions and performance of the athlets."
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/about/+page.svelte
> +		content="See the rules, the wall and the sport. Learn about the qualifications, the competitions and everything about it."
```suggestion
		content="You have never heard of speedclimbing? This is the perfect place to get up to speed and learn more about the sport!"
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/athlete/+page.svelte
> +		content="Detailed statistics of all athletes in the database. See their personal bests, competitions and more."
```suggestion
		content="Detailed statistics of all your favorite athletes. Find out their personal bests, competition results and more!"
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/competition/+page.svelte
> +	<title>Competetions - Overview</title>
```suggestion
	<title>Competitions - Overview</title>
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/competition/+page.svelte
> +		content="Everything about the last and upcoming competitions. See the results, the records and the calendar of the speedclimbing world."
```suggestion
		content="Everything about past and upcoming competitions. Get an overview of the whole schedule of speedclimbing events!"
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/stats/summary/+page.svelte
> +		content="See the summary of the current season and the all time statistics of the speedclimbing world.
```suggestion
		content="The latest and most relevant speedclimbing statistics at a glance.
```

2023-07-17 10:12 UTC, dorianim commented on src/routes/stats/summary/+page.svelte
> +		View who has the most medals and the world records."
```suggestion
		Find out who has won most medals and get to know the fastest climbers in the world!"
```

2023-07-17 16:24 UTC, allesklardy commented on src/app.html
> +		<meta name="keywords" content="Speedclimbing Statistics, Worldranking, IFSC" />
They aren't considered for Google, but i wanted to add them just in case

2023-07-17 16:41 UTC, dorianim commented on src/app.html
> +		<meta name="keywords" content="Speedclimbing Statistics, Worldranking, IFSC" />
Ok, I didn't know that.

2023-07-18 08:58 UTC, dorianim requested changes
Just one more thing:
Please add yourself to the contributers on the about us page :)

2023-07-19 20:19 UTC, dorianim approved these changes

2023-07-19 20:20 UTC, merged